# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLNmgg7GPkCwM3z2fM74W09UpvSCa_Od
"""

print("hi")

from collections import namedtuple
t=namedtuple("course",["name","technology"])
x=t("python","ml")
print(x)

print(x._asdict())
print(x)

print(t._make(["java","applet"]))

from collections import deque
d=deque()
print(d)
d.append("1")
d.append("2")
d.appendleft("3")
print(d)
d.pop()
d.popleft()
d.extend(["5","6"])
d.extendleft([9,89])
d.rotate(2)
print(d)

from collections import ChainMap
d1={"a":1,"b":2}
d2={"c":3,"d":4}
t=ChainMap(d1,d2)
print(t)
print(list(t))
d1={"a":1,"b":2}
d2={"a":3,"d":4}
t=ChainMap(d1,d2)
print(t)
print(list(t))#only unique keys

from collections import Counter
l=[1,2,2,2,4,1,5,5]
print(Counter(l))
c=Counter(l)
print(Counter(l))
print(list(c.elements()))
print(c.most_common())
s={1:1,5:1}
c.subtract(s)
print(c)

from collections import OrderedDict
od=OrderedDict()
od[1]=2
od[1]=3
od[1]="a"
od["3"]=4
print(od)
print(od.items())
print(od.values())
print(od.keys())

from collections import defaultdict

d=defaultdict(int)
d[1]=2
d[2]=3
d[3]=4
print(d)
print(d[1])
print(d[4])
d=defaultdict(list)
d[1]=2
d[2]=3
d[3]=4
print(d)
print(d[1])
print(d[4])
d=defaultdict(float)
d[1]=2
d[2]=3
d[3]=4
print(d)
print(d[1])
print(d[4])
d=defaultdict(str)
d[1]=2
d[2]=3
d[3]=4
print(d)
print(d[1])
print(d[4])

